FileVersion = 1

[Project]
Name = "duktape-beef"
DefaultNamespace = "duktape"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\duktaped.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\duktape.lib"]