FileVersion = 1

[Project]
Name = "duktape-beef"
DefaultNamespace = "duktape"

[Configs.Debug.Win64]
CLibType = "Dynamic"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\duktape.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\duktape.lib"]
